<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_all_sliders"
 *
 * Auto generated by Extension Builder 2016-12-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => '[NITSAN] All in One Slider Plugin',
	'description' => 'One of the only TYPO3 extension which provides to use most popular jQuery slider plugins at your website. This TYPO3 extension provides to configure sliders eg., Nivo Slider, Royal Slider, Owlcarousel, Sliderjs Slider & more will be available in an upcoming version.',
	'category' => 'plugin',
	'author' => 'Sanjay Chauhan [NITSAN Technologies]',
	'author_email' => 'sanjay@nitsan.in',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-8.9.9',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);